### ISSUE TITLE
conflict tests send create with lease and fail

### ISSUE THREAD

**Issue by eliadCohenVs** [Microsoft/WindowsProtocolTestSuites#100]
Conflict tests send create with lease and fail even my server does not support leasing.
The test name is as follow:
ConflictTestCaseS24
ConflictTestCaseS30
ConflictTestCaseS51
ConflictTestCaseS66
ConflictTestCaseS66
ConflictTestCaseS72
ConflictTestCaseS81
ConflictTestCaseS126
ConflictTestCaseS138
ConflictTestCaseS153

Pleas advise.
[ConflictTestCaseS126_lease.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/721853/ConflictTestCaseS126_lease.zip)

**Comment by yazeng** [comment]
I checked the trace, why in frame 79, you server sent STATUS_PENDING?

**Comment by eliadCohenVs** [comment]
I will check this one, but as i wrote in the other test like the ConflictTestCaseS81
The second create go with the lease oplock, i'm uploading a PCAP file.
[ConflictTestCaseS81_lease.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/722934/ConflictTestCaseS81_lease.zip)

**Comment by yazeng** [comment]
Yes, the second Create go with lease, the first one too. And you server should return OK for the second Create, instead of STATUS_PENDING. BTW, the first lease should not be broken.

**Comment by eliadCohenVs** [comment]
Why not?
Our server does not support leasing! So we downgrade to BATCH and for 2
BATCH the server should send STATUS_PENDING.
The question is why the tests sends lease if the server does not support
leasing?

On Jan 24, 2017 4:34 AM, "Yan Zeng" <notifications@github.com> wrote:

Yes, the second Create go with lease, the first one too. And you server
should return OK for the second Create, instead of STATUS_PENDING. BTW, the
first lease should not be broken.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/WindowsProtocolTestSuites/issues/100#issuecomment-274684200>,
or mute the thread

**Comment by yazeng** [comment]
When we design the Conflict test case, the purpose is to test the same file accessed by two clients, the two operation might be conflicting. Leasing is part of the conflict scenarios. So we assume server supports Leasing and the test cases do not check the server capability.
If I understand correctly, your server does not support leasing, and you still want to run those test cases.
One solution is that we can modify the cases and make them fail to "inconclusive" before sending the create request with Lease context, if the cases detect the server does not support leasing. So that the test cases which do not send Create with Lease, they will run normally; for other test case which do send Create with lease, they will fail to "inconclusive".

**Comment by eliadCohenVs** [comment]
You understand correctly.
Please make these tests fail to "inconclusive" like your other tests that
need leas and the server doesn't support leasing

On Jan 24, 2017 7:13 AM, "Yan Zeng" <notifications@github.com> wrote:

When we design the Conflict test case, the purpose is to test the same file
accessed by two clients, the two operation might be conflicting. Leasing is
part of the conflict scenarios. So we assume server supports Leasing and
the test cases do not check the server capability.
If I understand correctly, your server does not support leasing, and you
still want to run those test cases.
One solution is that we can modify the cases and make them fail to
"inconclusive" before sending the create request with Lease context, if the
cases detect the server does not support leasing. So that the test cases
which do not send Create with Lease, they will run normally; for other test
case which do send Create with lease, they will fail to "inconclusive".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/WindowsProtocolTestSuites/issues/100#issuecomment-274711765>,
or mute the thread

**Comment by yazeng** [comment]
Yes, I'll file a bug and fix it.
Thank you for reporting this issue.

**Comment by eliadCohenVs** [comment]
You are welcome.
