### ISSUE TITLE
CAShareName is not verified during test run

### ISSUE THREAD

**Issue by TesterTester111** [Microsoft/WindowsProtocolTestSuites#101]
Hi,

Seems that once CAShareName is set to a valid share name it's capability of continuous availability is never verified during the test run.
For example test RequestPersistentHandleTestCaseS74 run against Server2012R2 share which is not CA, but it's name is set in CAShareName . According to spec persistent handle should not be granted, but test expects it, since no actual check for CS share capability is done.

[RequestPersistentHandleTestCaseS74.txt](https://github.com/Microsoft/WindowsProtocolTestSuites/files/732442/RequestPersistentHandleTestCaseS74.txt)

please rename gif to pcap:
![requestpersistenthandletestcases74](https://cloud.githubusercontent.com/assets/25079571/22334010/9c3f4c52-e3e1-11e6-890b-546e9f8e8797.gif)

Thanks,
Lilia

**Comment by yazeng** [comment]
Hi Lilia,
Sorry for my late reply due to Chinese New Year.
Yes, you are right, the test cases do not verify if the share is really a CA share. We assume that CAShareName is a CA share.
In my opinion, if you do not have a CA share, you do not need to run case like RequestPersistentHandleTestCaseS74. Or you can leave it empty, then such cases will fail inconclusive.

Thanks,
Yan

**Comment by TesterTester111** [comment]
Hi Yan,
It just seems not consistent, you check all flags in responses, like capabilities and so on, 
why this one is left out?
Regards,
Lilia

**Comment by yazeng** [comment]
Hi Lilia,
Yes, sounds reasonable.
I'll file a bug and see what we can do.

Thank you for reporting this issue.
Yan

**Comment by yazeng** [comment]
@TesterTester111 , Lilia, the bug is fixed and pushed to staging branch.
You could have a try when you have time.

**Comment by TesterTester111** [comment]
Great, thank you.

**Comment by yazeng** [comment]
Close this issue since no update for a long time.
