### ISSUE TITLE
Error generated from XML typo (easy fix).

### ISSUE THREAD

**Issue by c-r-h** [Microsoft/WindowsProtocolTestSuites#102]
When building the MS-SMB test suite per the instructions, an error message is generated:
```
"C:\Users\Administrator\WindowsProtocolTestSuites\TestSuites\MS-SMB\src\deploy\deploy.wixproj"
  (Clean;Rebuild target) (1) ->
    (Compile target) -> C:\Users\Administrator\WindowsProtocolTestSuites\TestSuites\MS-SMB\src\deploy\TestSuitePrivacyStatementLowMsiVersionDlg.wxs(19): error CNDL0104: Not a valid source file; detail: The 'Control' start tag on line 17 position 10 does not match the end tag of 'Text'. Line 19, position 6. [C:\Users\Administrator\WindowsProtocolTestSuites\TestSuites\MS-SMB\src\deploy\deploy.wixproj]
```
To fix, delete line 19 in file .../MS-SMB/src/Deploy/TestSuitePrivacyStatementLowMsiVersionDlg.wxs

That line contains a closing <\/Text> tag with no matching opening tag.

**Comment by yazeng** [comment]
Hi Chris,

Thank you for catching this issue for us.
Quick fix is delivered. Meanwhile, we'll refine our regression test to avoid such issues in the future.

Thanks,
Yan
