### ISSUE TITLE
Unable to load the test container

### ISSUE THREAD

**Issue by akilanmaris** [Microsoft/WindowsProtocolTestSuites#106]
When I try running the RunAllTestCases in MS-SMB Testsuite, I'm getting the following error.

**C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5142.0\Batch>"C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\..\IDE\mstest" /category:"Traditional|Win7_Win2K8R2" /testcontainer:..\Bin\MS-SMB_ServerTestSuite.dll /runconfig:..\Bin\ServerLocalTestRun.testrunconfig
Microsoft (R) Test Execution Command Line Tool Version 11.0.50727.1
Copyright (c) Microsoft Corporation. All rights reserved.

Loading ..\Bin\ServerLocalTestRun.testrunconfig...
Loading ..\Bin\MS-SMB_ServerTestSuite.dll...
..\Bin\MS-SMB_ServerTestSuite.dll
Unable to load the test container '..\Bin\MS-SMB_ServerTestSuite.dll' or one of its dependencies. Error details: System.TypeLoadException: Could not load type 'Microsoft.Protocols.TestTools.PtfTestClassBase' from assembly 'Microsoft.Protocols.TestTools.VSTS, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.**

**Comment by yazeng** [comment]
Thanks for contacting us.
What kind of PTF do you build? Is it ForModel version or NonModel version?
SMB test suite needs PTF which is "ForModel" version.
You can download the .msi file directly from here:
https://github.com/Microsoft/ProtocolTestFramework/releases

And you can also download SMB test suite here:
https://github.com/Microsoft/WindowsProtocolTestSuites/releases

Thanks,
Yan

**Comment by yazeng** [comment]
Close this issue since Akilan can run the test cases now.
