### ISSUE TITLE
Improvements to PTM CLI

### ISSUE THREAD

**Issue by bentsi** [Microsoft/WindowsProtocolTestSuites#114]
Hi,
Following improvements are needed for PTM cli in order make it more usable for tests automation:

- Ability to run specific test category
`-c | -category Run specific tests category`
- Return error when mandatory input arguments are not provided
For example if profile is not provided the error output is not clear:
> PS C:\Program Files (x86)\Protocol Test Manager\bin> .\PtmCli.exe -s -r result.txt
> ERROR:
> Value cannot be null.
> Parameter name: path

**Comment by JiajunW** [comment]
Thanks for reporting. I am working the the fix.

**Comment by JiajunW** [comment]
The categories parameter is added in dbb498d. For example, using `-categories fsrvq,smb311` will let PTM to run all FSRVP *and* Smb311 cases.

Mandatory parameter fix is in ebba442. Now, only `profile` is mandatory, if it is not set, an error `The value of argument Profile is missing.` will shown.

You can download the latest source code and build PTM yourself to test the fix :)

**Comment by JiajunW** [comment]
Close this issue since no update for a long time. Feel free to reopen it if the problem still exists.
