### ISSUE TITLE
DifferentShareFromSMBBasic 

### ISSUE THREAD

**Issue by TesterTester111** [Microsoft/WindowsProtocolTestSuites#120]
Hi,

Running AppInstanceIdTestCaseS130 test and some others I get 

> Assert.Inconclusive is inconclusive. The value of DifferentShareFromSMBBasic is empty.

But I can't find **DifferentShareFromSMBBasic**  field in Configure Test Cases, where is it?

Thanks,
Lilia

**Comment by yazeng** [comment]
Hi Lila,
There is a config named "DifferentShareFromSMBBasic".
If you use PTM to do the configuration, see the screenshot:
![snip_20170808092433](https://user-images.githubusercontent.com/10937464/29052284-a27c9174-7c1b-11e7-8d0b-e4b530363638.png)

If you modify the config file manually, it is in \WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.deployment.ptfconfig

**Comment by TesterTester111** [comment]
Thanks, found it!
