### ISSUE TITLE
FileServer does not run

### ISSUE THREAD

**Issue by tymok** [Microsoft/WindowsProtocolTestSuites#122]
Hello.

I am developing a SMB2 server implemetation and want to test its compatibility with WindowsProtocolTestSuites.
Actullay I got some error messages when I try to run FileServer test after installing all prerequsites.
I could find no meaningful solution for this problem by googling and MSDN search so I request you to check the log.
Any opinion will be appreciated.

Regards,
Taeyang Mok

--------

C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\2.0.66.0\Batch>Domain_RunAllTestCases.cmd
Define the command to run file sharing test suite
Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
Copyright (c) Microsoft Corporation.  All rights reserved.

테스트 실행을 시작하는 중입니다. 잠시 기다려 주십시오...
경고: 다음 이유로 인해 TIP를 인스턴스화할 수 없으므로 TestTypes\13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b을(를) 로드할 수 없습니다. System.IO.FileNotFoundException:
파일이나 어셈블리 'Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 또는 여기에 종속되
어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 파일을 찾을 수 없습니다.
**_@ It seems that Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip is not found._**
파일 이름: 'Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   위치: System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, I
ntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   위치: System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr
 pPrivHostBinder, Boolean loadTypeFromPartialName)
   위치: System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   위치: System.Type.GetType(String typeName, Boolean throwOnError)
   위치: Microsoft.VisualStudio.TestTools.TestManagement.TipDelayLoader.LoadTip()

=== 미리 바인딩된 상태 정보 ===
로그: DisplayName = Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
로그: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/
로그: 초기 PrivatePath = NULL
호출 어셈블리: (Unknown).
===
로그: 이 바인딩은 default 로드 컨텍스트에서 시작됩니다.
로그: 응용 프로그램 구성 파일 C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe.Config을(
를) 사용합니다.
로그: 호스트 구성 파일 을(를) 사용합니다.
로그: C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config에서 컴퓨터 구성 파일을 사용합니다.
로그: 사후 정책 참조: Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Microsoft.VisualStudio.QualityTools.T
ips.UnitTest.Tip.DLL을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Microsoft.VisualStudio.QualityTools.T
ips.UnitTest.Tip/Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip.DLL을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Extensions/Microsoft.VisualStudio.Qua
lityTools.Tips.UnitTest.Tip.DLL을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Extensions/Microsoft.VisualStudio.Qua
lityTools.Tips.UnitTest.Tip/Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip.DLL을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Microsoft.VisualStudio.QualityTools.T
ips.UnitTest.Tip.EXE을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Microsoft.VisualStudio.QualityTools.T
ips.UnitTest.Tip/Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip.EXE을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Extensions/Microsoft.VisualStudio.Qua
lityTools.Tips.UnitTest.Tip.EXE을(를) 다운로드합니다.
로그: 새 URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Extensions/Microsoft.VisualStudio.Qua
lityTools.Tips.UnitTest.Tip/Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Tip.EXE을(를) 다운로드합니다.

경고: ..\Bin\MS-DFSC_ServerTestSuite.dll ..\Bin\MS-SMB2_ServerTestSuite.dll ..\Bin\MS-SMB2Model_ServerTestSuite.dll ..\Bin\MS-FSA_ServerTestSuite.dll에서 테스트
를 사용할 수 없습니다. 설치된 테스트 Discoverer와 Executor, 플랫폼 및 프레임워크 버전 설정이 적절한지 확인한 후에 다시 시도하세요.
**_@ It indicates that version configurations of test Discoverer, Executor, platform and framework need to be checked._**

정보: 또한 테스트 Discoverer 및 Executor가 vsix 확장과 같은 컴퓨터에 설치되어 있으며 설치에서 vsix 확장을 지원하는 경우에는 '/UseVsixExtensions' 명령을 지정할
수 있습니다(예: vstest.console.exe myTests.dll /UseVsixExtensions:true).

**Comment by tymok** [comment]
For your information, some googling results suggest to install NUnit 3 Test Adapter(https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter) but it seems that the extension cannot be installed with Microsoft Visual Studio Express 2015 for Windows Desktop.

2017-09-07 오전 10:48:07 - Microsoft VSIX Installer
2017-09-07 오전 10:48:07 - -------------------------------------------
2017-09-07 오전 10:48:07 - Initializing Install...
2017-09-07 오전 10:48:08 - 확장 정보...
2017-09-07 오전 10:48:08 - 	Identifier      : NUnit.NUnit3TestAdapter
2017-09-07 오전 10:48:08 - 	Name            : NUnit 3 Test Adapter
2017-09-07 오전 10:48:08 - 	Author          : Charlie Poole, Terje Sandstrom
2017-09-07 오전 10:48:08 - 	Version         : 3.8.0.0
2017-09-07 오전 10:48:08 - 	Description     : NUnit 3 adapter for running tests in Visual Studio. Works with NUnit 3.x.
For running NUnit 2 tests, use the NUnit 2 adapter.
2017-09-07 오전 10:48:08 - 	Locale          : en-US
2017-09-07 오전 10:48:08 - 	MoreInfoURL     : https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter
2017-09-07 오전 10:48:08 - 	InstalledByMSI  : False
2017-09-07 오전 10:48:08 - 	SupportedFrameworkVersionRange : [4.5,)
2017-09-07 오전 10:48:08 - 
2017-09-07 오전 10:48:08 - 	지원되는 제품         : 
2017-09-07 오전 10:48:08 - 		Microsoft.VisualStudio.Community
2017-09-07 오전 10:48:08 - 			Version : [11.0,16.0)
2017-09-07 오전 10:48:08 - 		Microsoft.VisualStudio.Pro
2017-09-07 오전 10:48:08 - 			Version : [11.0,16.0)
2017-09-07 오전 10:48:08 - 		Microsoft.VisualStudio.Enterprise
2017-09-07 오전 10:48:08 - 			Version : [11.0,16.0)
2017-09-07 오전 10:48:08 - 
2017-09-07 오전 10:48:08 - 	참조              : 
2017-09-07 오전 10:48:08 - 
2017-09-07 오전 10:48:08 - 적용 가능한 제품을 검색하고 있습니다...
2017-09-07 오전 10:48:08 - 설치된 제품 찾음 - Microsoft Visual Studio Express 2015 for Windows Desktop
2017-09-07 오전 10:48:08 - 설치된 제품 찾음 - 전역 위치
2017-09-07 오전 10:48:08 - VSIXInstaller.NoApplicableSKUsException: 이 확장은 현재 설치되어 있는 제품에 설치할 수 없습니다.
@ This extension cannot be installed
   위치: VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   위치: VSIXInstaller.App.InitializeInstall()
   위치: System.Threading.Tasks.Task.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()

**Comment by yazeng** [comment]
Hi Taeyang,

I haven't seen such error before. Could you try install VS 2015 test agent, instead of VS 2015 express?

Thanks,
Yan

**Comment by tymok** [comment]
Dear Zeng,

Thanks for your quick response.
After doing version up VS to VS 2017 community and installing some extensions,
Fileserver runs. :+1: 
Though it seems that there are some configuration issues, I will look into it.
