### ISSUE TITLE
FileServer : cannot run test suites for some categories

### ISSUE THREAD

**Issue by tymok** [Microsoft/WindowsProtocolTestSuites#128]
Hello.

I found that I could not run test for some categories of FileServer.
Please check the following list.

> [ LeasingV1	0	0	0	0	fail to run TC
LeasingV2	0	0	0	0	fail to run TC
FSRVP	0	0	0	0	fail to run TC
SWN	0	0	0	0	fail to run TC
RsvdVersion1	0	0	0	0	fail to run TC
RsvdVersion2	0	0	0	0	fail to run TC
SQOS	0	0	0	0	fail to run TC
Auth	0	0	0	0	fail to run TC
KerberosAuthentication	0	0	0	0	fail to run TC
FileAccessCheck	0	0	0	0	fail to run TC
FolderAccessCheck	0	0	0	0	fail to run TC
ShareAccessCheck	0	0	0	0	fail to run TC
CBAC	0	0	0	0	fail to run TC
Cluster	0	0	0	0	fail to run TC ] 

Other TCs run well. Could you share what the problem could be?
Error log and test enviroment are as follows:

>** Error log
C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\2.0.66.0\Batch\..\Bin\MS-DFSC_ServerTestSuite.dll C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\2.0.
66.0\Batch\..\Bin\MS-SMB2_ServerTestSuite.dll C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\2.0.66.0\Batch\..\Bin\MS-SMB2Model_ServerTestSuite.dll C:\Mic
rosoftProtocolTests\FileServer\Server-Endpoint\2.0.66.0\Batch\..\Bin\MS-FSA_ServerTestSuite.dll에서 테스트를 사용할 수 없습니다. 테스트 Discoverer와 Executor가
등록되었고 플랫폼 및 프레임워크 버전 설정이 적절한지 확인한 후 다시 시도하세요.
** This means "No test is available in ~~.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again."
/TestAdapterPath 명령을 사용하여 테스트 어댑터 경로도 지정할 수 있습니다. 예: /TestAdapterPath:<pathToCustomAdapters>.

>** Environment
Windows 7 Ultimate K
WindowsProtocolTestSuites-2.0.66.0
VS community 2017
VS test agent 2017

**Comment by chenlu0616** [comment]
Hi, Taeyang

Since there is some Korean embed in the error log, I cannot see what the exact dll name that cannot be loaded (The categories you cannot run probably are included in these dlls).  
As you have mentioned that some of the TCs could run and others are not, please make sure that you are using the correct version of Protocol Test Framework(PTF) to compile all the dlls and run the test cases. You are using WindowsProtocolTestSuites-2.0.66.0, the corresponding PTF version is 1.0.5500.0  (Link: https://github.com/Microsoft/ProtocolTestFramework/releases .Use ProtocolTestFrameworkInstallerForModel.msi for FileServer). 

Let me know if it does work for you.

Thanks,
Lu

**Comment by tymok** [comment]
Hello, Lu

Thanks for the quick response.
Actually I was already using PTF version 1.0.5500.0 when I saw the error messages. 
I re-install PTF in case but still there is the same problem.

By the way where I got the problem is as below: (in RefreshTestConfig.cmd file)

`    REM workgroup environment
    set RunFileSharingTestSuite=%vspath%"..\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" ..\Bin\MS-DFSC_ServerTestSuite.dll ..\Bin\MS-SMB2_ServerTestSuite.dll ..\Bin\MS-SMB2Model_ServerTestSuite.dll ..\Bin\MS-FSA_ServerTestSuite.dll /Settings:..\Bin\ServerLocalTestRun.testrunconfig /Logger:trx`

So problemetic dlls are MS-DFSC_ServerTestSuite.dll, MS-SMB2_ServerTestSuite.dll, MS-SMB2Model_ServerTestSuite.dll, and MS-FSA_ServerTestSuite.dll.
I built FileServer Testsuites and overwrite dlls with what I built in case.
But it's not resolving the issues.

Is there any other thing that I could try? 

Best Regards,
Taeyang Mok

**Comment by chenlu0616** [comment]
Hi, Taeyang

Noticed you are using test agent 2017. I just checked the  RefreshtestConfig.cmd file and found that there is no definition of vs path for visual studio 2017(maybe we should add to support later), which may cause the problem. For ourselves, we normally use Visual Studio(or Test Agent) 2015 or 2012 (with Update 4 installed). So suggest you try to run with Test agent 2015 or 2012.

Thanks,
Lu

**Comment by tymok** [comment]
Actually I added an environment variable for vs 2017 by myself. So I think it's not a cause of the problem.
About VS 2015 & VS TA 2015, I will try it and share the result.

Thanks,
Taeyang Mok

**Comment by tymok** [comment]
works fine with VS 2015 and VS TA 2015
