### ISSUE TITLE
Can I run MS-SMB testsuites by feature like FileServer testsuites?

### ISSUE THREAD

**Issue by tymok** [Microsoft/WindowsProtocolTestSuites#131]
Hello,

Thanks to your support, I ran MS-SMB testsuites successfully.

By the way, Can I run MS-SMB testsuites by feature like FileServer testsuites?
Categories that MS-SMB testsuites provide have too many TCs to debug.

Best Regards,
Taeyang Mok

**Comment by chenlu0616** [comment]
Hi, Taeyang

MS-SMB testsuite is an old testsuite which does not have feature related categories like FileServer test suite. Currently we just support three categories for SMB:
**Traditional            All traditional test cases
Win7_Win2K8R2          Model based cases that client is Win7, SUT is Win2K8R2
Win7_Win2K8            Model based cases that client is Win7, SUT is Win2K8_**

You can select the category by running "Run MS-SMB Server-Test Cases By Category" batch command.

Thanks,
Lu

**Comment by tymok** [comment]
Thanks for the comment.
