### ISSUE TITLE
"The imported project "C:\Microsoft.Cpp.Default.props" was not found" Error occurs while building MS_SMBD testsuite

### ISSUE THREAD

**Issue by bharath993** [Microsoft/WindowsProtocolTestSuites#133]
I am trying to build the MS-SMBD testsuite 

I have ran the installprerequisiters script and had installed SpecExplorer

When running the build.cmd i get the following errors

PS C:\Users\Administrator\Desktop\WindowsProtocolTestSuites-staging\TestSuites\MS-SMBD\src> .\build.cmd

C:\Users\Administrator\Desktop\WindowsProtocolTestSuites-staging\ProtoSDK\RDMA\Rdma.vcxproj(53,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path
 in the <Import> declaration is correct, and that the file exists on disk.

Looks like "Microsoft.Cpp.Default.props" is missing in the msbuild folder

**Comment by chenlu0616** [comment]
Hi,

The Rdma.vcxproj project has some dependencies of platform toolset. Suggest install Visual Studio 2013 in your environment to build 64 bit binaries and run(as Noted in "MS-SMBD_ServerUserGuide.md"), or else you have to modify some project configurations manually, which is complicated. 

Besides,  before building, make sure to put the files "ndspi.h" and "ndstatus.h" under the path "%TestSuiteRoot%ProtoSDK\RDMA\include" as build cmd hints.

Thanks,
Lu

**Comment by bharath993** [comment]
Thank You, it worked 👍
