### ISSUE TITLE
Importing of OPNs into Microsoft Message Analyzer fails

### ISSUE THREAD

**Issue by queso1307** [Microsoft/WindowsProtocolTestSuites#140]
I copied all files from RDP/Client-Endpoint/3.18.3.0/Data/SuperLogViewer/OPNs to the User AppData Directory. 
When i start the MMA i get following Error Message:
`Error
C:\Users\Administrator\AppData\Local\Microsoft\MessageAnalyzer\OPNAndConfiguration\Opns\Microsoft\Windows\RemoteDesktop\Protocol_Test_Suite.opn(96,36-96,53):  undeclared 'DecodeEtwKeywords`'

I do not know if i did something wrong, but i would appreciate if you could take a look why this happens.

RDP Client TestSuite Build 3.18.3.0
MMA: 1.4
PTF: commit f02506bc2f72dbd90df360a0702af6ac92c55f88

Thank you very much in advance

**Comment by huiren-jiang** [comment]
Hi queso1307,

I have just tried to repro you issue and the cause might be below,

According to RDP_ClientUserGuide.md, 

Copy C:\MicrosoftProtocolTests\RDP\Client-Endpoint\ < version # > \Data\SuperLogViewer\OPNs\ * .opn to < MMA installation directory > \OPNAndConfiguration\OPNs\Microsoft\Windows\RemoteDesktop and start the MMA.

In my test environment, that folder is "C:\Program Files\Microsoft Message Analyzer\OPNAndConfiguration\OPNs\Microsoft\Windows\RemoteDesktop" and I managed to capture all the logs could be capture by MMA.

Could you please remove the corresponding OPNs file from User AppData and try copying to the path given in guide again?

Thanks

**Comment by yazeng** [comment]
Close this issue since no response for a long time.
