### ISSUE TITLE
PTM config saved incorrectly and PtmCli doesn't run all tests and shows no errors

### ISSUE THREAD

**Issue by rajaandra** [Microsoft/WindowsProtocolTestSuites#141]
Hi,
 
I’m trying to run Windows Protocol test Suites and am able to run them successfully using GUI interface of PTM. But when I try to load the saved config, the SMB Dialects are not selected as seen in the attached Screenshot. How do I save the profile so that it will load the SMB dialects and all the test cases?? I’m using this profile to run using PtmCli and I see none of the SMB2 tests run and I think this is probably because the test suites are not selected. Am attaching the screen output below. Can you please help me out so that I can run the tests thru CLI? (I’ve modified IP/FQDN/passwd in .ptm file)
 
Pl. let me know if you need any details.
 
Test setup details:
 
Windows 2012
Protocol Test Manager version 3.18.3.0 ( as seen in attached screenshot)
Protocol Test Suites downloaded from https://github.com/Microsoft/WindowsProtocolTestSuites/releases

[pl. rename t1.txt to t1.ptm]  
 
Thank you for your time.

Thanks,
Raja

 
![ptmcli](https://user-images.githubusercontent.com/39289246/40035857-b43778f6-57b8-11e8-8c3d-92b11ed50847.png)
![ptm](https://user-images.githubusercontent.com/39289246/40035858-b44e84f6-57b8-11e8-8904-ab6f268bbc73.png)
[t1.txt](https://github.com/Microsoft/WindowsProtocolTestSuites/files/2003402/t1.txt)

**Comment by HsuanyaTsai** [comment]
Hi Raja,

Thanks for reporting this issue.
It's a bug in PTM and we will find out how to fix it.
Please use previous version (2.0.66.0) of TestSuites/PTM for testing while waiting for the fix.
https://github.com/Microsoft/WindowsProtocolTestSuites/releases/tag/2.0.66.0

Thanks.

Regards,
Michael
