### ISSUE TITLE
Can the .ptm files be modified manully? [question]

### ISSUE THREAD

**Issue by rajaandra** [Microsoft/WindowsProtocolTestSuites#143]
Hi,

Is there a way to modify .ptm file generated and use it with PtmCli?? I want to edit the exported .ptm config file and update host/domain/user details and use it with PtmCli? Right now, when I try to load the edited .ptm file or run using PtmCli, I get an error that the file is corrupted. Is there a way to do this?? The config file needs to be generated on run time based on user provided config details, so need a way to create/update .ptm file using CLI. Pl. let me know what are the options to do this.

Thank you,
Raja

**Comment by JiajunW** [comment]
Hi Raja

Actually `.ptm` file is a zip package. If you want to modify a `.ptm` file, you can:

1. Firstly unzip it.
2. You can find a file ending with `.deployment.ptfconfig` under ptfconfig folder.
3. Update the corresponding value in that file.
4. Create a zip package (keeping the original folder structure).
5. Rename the suffix from `zip` to `ptm`.

You can now use the new `.ptm` file in PtmCli.

**Comment by rajaandra** [comment]
Hi JaijunW, Thank you for your reply. I was able to use the suggestion above and create new .ptm file and use it in PtmCli.

Thanks!
