### ISSUE TITLE
How to get log files when using PtmCli? [Question]

### ISSUE THREAD

**Issue by rajaandra** [Microsoft/WindowsProtocolTestSuites#145]
Hi,

When the tests are run using PtmCli, how can we get the test results log? The only option I see is to get the report which only shows whether the test passed or failed etc. If a test is failed, I see ErrorStackTrace, ErrorMessage and StandardOut in GUI for the failed test case and StandardOut console log for passed test cases. Is there a way to get this when run thru PtmCli??

Thank you,
Raja

**Comment by yazeng** [comment]
Hi Raja,

The log files should be found under your test suite install folder.
E.g., "C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\3.18.6.0\HtmlTestResults\"
Let use know if you have any further questions.

Thanks,
Yan

**Comment by rajaandra** [comment]
Hi Yan,

Thank you, I'll take a look.  Couple of more questions
1. Can you run multiple tests at the same time? I mean create two or more .ptm files pointing to different servers and run them using PtmCli at the same time?
2. Would the test results be consistent if we do step 1?
3. Is there a way to check the progress of the tests when ran using PtmCli?

Thanks,
Raja

**Comment by yazeng** [comment]
Hi Raja,
1&2: No, we do not support this feature. We cannot run multiple .ptm files at the same time.
3: No, there is no way to check the progress for now. But I think it's a good suggestion. I'll file a bug and fix it later.

Thanks,
Yan

**Comment by rajaandra** [comment]
Hi Yan,

Thank you for the replies. Is there any plan to support 1&2? Running multiple tests at same time would be helpful.

Thanks,
Raja

**Comment by yazeng** [comment]
Hi Raja,
Currently we do not have such a plan. But I'll create a work item and put it to our backlog.

Thanks,
Yan

**Comment by rajaandra** [comment]
Hi Yan,

Thank you for your responses, they are helpful. Appreciate them. Going ahead and closing this query.

Thanks,
Raja
