### ISSUE TITLE
User guide for running the WPTS from Powershell (and remotely)

### ISSUE THREAD

**Issue by c-r-h** [Microsoft/WindowsProtocolTestSuites#146]
I just saw a very nice demo of PtmCli, which can be used to run the test suites from Powershell.

I would like to have a HowTo to describe both how to use PtmCli and how to use it from a remote machine (Linux or Windows).

**Comment by JiajunW** [comment]
Hi Chris,

The guide for using PowerShell Core to remotely trigger test suite is documented in our wiki. https://github.com/Microsoft/WindowsProtocolTestSuites/wiki/Remotely-Trigger-Test-Suites

You can give it a try. :)
