### ISSUE TITLE
Prerequisites installation order

### ISSUE THREAD

**Issue by slowfranklin** [Microsoft/WindowsProtocolTestSuites#148]
For the records as discovered at an interop event, the order of prerequisites seems to be wrong.

Currently this is:
* Protocol Test Framework
* Visual Studio 2017

It must be:
* Visual Studio 2017
* Protocol Test Framework

**Comment by lumengyan** [comment]
Thanks for reporting the issue! We will update the order and provide more details to install VS2017.

**Comment by yazeng** [comment]
Readme is updated.
Could you please have a check when you have time?

Best Regards,
Yan

**Comment by slowfranklin** [comment]
Lgtm, thanks!
