### ISSUE TITLE
Incorrect default value of VerifySUTDisplay.IQA.AssessValueThreshold in RDP default settings

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#169]
On configuration testsuite Protocol Test Manager shows default values of configuration settings.
Default value of *VerifySUTDisplay.IQA.AssessValueThreshold* is equal to 0.98 but in a [RDP Client Test Suite User Guide](https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_ClientUserGuide.md#required-configuration-settings) described possible values: "should be in [0, 1]".

Protocol Test Manager 1.0.6000.0
Microsoft RDP Client Endpoint TestSuite 3.19.3.0

**Comment by sweeetday** [comment]
Hi, Ligurio
The value of VerifySUTDisplay.IQA.AssessValueThreshold is a float number in the range of [0, 1]. So the default value 0.98 is a correct value in this range. 
The user guide and ptfconfig file have been updated with more clear description about your issue.  See the commit https://github.com/microsoft/WindowsProtocolTestSuites/commit/b38aadeca4e737acc853bf9be3ea46cc7480c379 . Hope the change helps. 
Thanks for the feedback.
