### ISSUE TITLE
Visual Studio 2019 prerequisites

### ISSUE THREAD

**Issue by jtmoon79** [microsoft/WindowsProtocolTestSuites#180]
Currently the [`README.md`](../blob/a2f100e4e118d0b602fe4bf46a3479852b7983aa/README.md#prerequisites) has prerequisite software for _Visual Studio 2017_.  However, _Visual Studio 2017_ has been replaced by _Visual Studio 2019_.

Could you update the `README.md` to include prerequisites for _Visual Studio 2019_?

**Comment by huiren-jiang** [comment]
Hi James,

We will update the recommended prerequisites to VS2019 in readme.md later. Thanks for your suggestion.

Windows Protocol Test Suites Development Team

**Comment by huiren-jiang** [comment]
Hi James,

We have updated the prerequisites part in readme.md and related scripts so that all test suites could support Visual Studio 2019.

Best Regards,

Windows Protocol Test Suites Development Team
