### ISSUE TITLE
support test result output in a formalized format

### ISSUE THREAD

**Issue by jtmoon79** [microsoft/WindowsProtocolTestSuites#182]
### Problem

Test result output is currently in two forms.

- a line-oriented text file
```
PASSED    BVT_Encryption_SMB311
FAILED    BVT_Encryption_SMB311_CCM 
```
- an HTML file

<br/>

1. **These HTML output is difficult to parse.**
1. **The text file can be parsed but does not include any extra information beyond _PASSED_ and _FAILED_.**

<br />

### Solution

Allowing the user to specify a file format more readily parse-able is necessary for automated tools.  Add this to the `PtmCli.exe` program.

Most tools support both XML format and json format.

I suggest also supporting XML format that uses the [jUnit XML schema](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd).  Most programming languages have libraries for reading the jUnit files.
There is also the [xUnit XML schema](https://xunit.net/docs/format-xml-v2) which is a very well designed test results format.

It is important to include error output information for failed tests. This allows test engineers and automated tools to more easily create and update bugs in a bug tracking system.

**Comment by ligurio** [comment]
Good idea! Existed output can be easily converted to [TestAnythingProtocol](https://testanything.org/tap-version-13-specification.html) and probably will not require many time for development.
See also [Everything you need to know about software testing report formats]( https://github.com/ligurio/testres/wiki/Everything-you-need-to-know-about-software-testing-report-formats).

**Comment by JiajunW** [comment]
I am currently implementing this feature, formalized test results will be available in both PTM and PtmCli.

**Comment by JiajunW** [comment]
This feature has been added in commit 1cff6060a4d9c6f9fefaf22aecf7a59edf2553bb. You can now export the test result after executing test cases.

![Export test report](https://user-images.githubusercontent.com/906878/63756012-3d6d8180-c8ea-11e9-9a5c-c76edcf07ba9.png)

![Choose report format](https://user-images.githubusercontent.com/906878/63756028-43636280-c8ea-11e9-8897-d0381199ab4d.png)

Currently, xUnit and json format are supported, as well as the existing plain test report. You can also easily add the format you want. :)

For PtmCli, you can also specify `-f xunit -r report.xml` in command line argument to save the report file as `report.xml` in xUnit format.

This feature will be included in the next coming release.

Best Regards,
Windows Protocol Test Suites Development Team
