### ISSUE TITLE
describe Powershell commands to setup test for SMB2

### ISSUE THREAD

**Issue by jtmoon79** [microsoft/WindowsProtocolTestSuites#189]
The documentation _Setup SUT_ within _Test Suite Introduction_ describes what is needed.
It would be very helpful if it provided the Powershell commands to run.

For example,

> Create a share with Oplock Force Level 2 enabled 
> It's used for some cases when testing Oplock feature of SMB2 protocol.
> a. Create a share **ShareForceLevel2** on node01. 
> b. Share with read/write access to Admin User. 
> c. Enable **FORCE_LEVELII_OPLOCK** on this share.

Can you provide an example Powershell command that does this?  I would prefer to use native Powershell commands.

I noticed file [`./FileServer/Setup/Scripts/Create-SMB2Env.ps1`](https://github.com/microsoft/WindowsProtocolTestSuites/blob/712d47e/TestSuites/FileServer/Setup/Scripts/Create-SMB2Env.ps1).  However, this script file appears to have hardcoded paths.  e.g.

    Write-Info.ps1 "Create share folder: K:\SMBReFSShare"
    Create-SMBShare.ps1 -name "SMBReFSShare" -Path "K:\SMBReFSShare" -FullAccess "$fullAccessAccount"

**Comment by huiren-jiang** [comment]
Hi James,

Thanks for your feedback. We will plan to update the user guide to give extra instructions on which PowerShell script could be used for each configuration step. Please notice that the configuration scripts we open-sourced are an example illustrating how to configure Windows SUT, descriptive steps could not be replaced by these scripts for common interoperability testing against non-Windows SUTs. 

Considering your questions,

1. For Oplock force level 2, [Config-ForceLevel2.ps1](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/FileServer/Setup/Scripts/Config-ForceLevel2.ps1) could be used. Currently, there is no native PowerShell command to do such configuration and actually it calls to [ShareUtil](https://github.com/microsoft/WindowsProtocolTestSuites/tree/staging/TestSuites/FileServer/ShareUtil).

2. Volume K is created for ReFS testing and we could make it configurable.

Best Regards,

Windows Protocol Test Suites Development Team
