### ISSUE TITLE
Format of `playlist.xml` is not described in documentation

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#190]
There is a console utility to run tests without GUI - [PtmCli.exe](https://github.com/Microsoft/WindowsProtocolTestSuites/wiki/PtmCli). It requires two files for running: file with configuration and file with a list of tests to run. First file can be copied from a directory with results, it is `ptfconfig`. Second file is an XML file with a list of tests. What is an XML schema for it?

**Comment by JiajunW** [comment]
To use PtmCli, you need a *PTM profile*.

You can export one in the GUI version of PTM, as shown in the picture below.

![image](https://user-images.githubusercontent.com/906878/61866990-cfa7f180-af08-11e9-9c0a-55a06650ef71.png)

You can specify the profile using `-p`. For example: `PtmCli.exe -p test.ptm`.

For more PtmCli usage, please check out the [wiki page](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/PtmCli).

**Comment by ligurio** [comment]
@JiajunW Thanks a lot! I believe it would be useful to place that info on wiki too.

**Comment by JiajunW** [comment]
Hi Sergey,

I have added the step to export a profile in [PtmCli wiki page](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/PtmCli#export-test-profile).

Best Regards,
Windows Protocol Test Suites Development Team
