### ISSUE TITLE
Broken links in Wiki

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#192]
broken links on page https://github.com/microsoft/WindowsProtocolTestSuites/wiki#rdp:

https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/docs/RDP_ClientUserGuide.md should be https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_ClientUserGuide.md

https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/docs/RDP_Overview_ClientTestDesignSpecification.md should be https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_Overview_ClientTestDesignSpecification.md

**Comment by yazeng** [comment]
Hi Sergey,
   Thanks for reporting it. We've updated the page.

Best Regards,
Windows Protocol Test Suites Development Team
