### ISSUE TITLE
Little Confusion

### ISSUE THREAD

**Issue by devcoinfet** [microsoft/WindowsProtocolTestSuites#198]
#endregion SVC Manager control

        #endregion help methods

        #region connection operations
        /// <summary>
        /// Build a RDPBCGR connection, includes all 23 connection messages.
        /// Support both Standard RDP Security and Enhanced Security.
        /// </summary>
        /// <param name="virtualChannels">The virtual channels user wants to join. This argument can be null.
        /// If it is null, then no channel will be joined.</param>
        /// <param name="alternateShell">Variable-length path to the executable file of an alternate shell.
        /// This argument can be null. If it is null, then the size field will be 0, the content field will
        /// be the same with TD.</param>
        /// <param name="workingDir">Variable-length directory that contains the executable file specified in the 
        /// AlternateShell field or any related files (the length in bytes is given by the cbWorkingDir field).
        /// This argument can be null. If it is null, then the size field will be 0, the content field will
        /// be the same with TD.</param>
        /// <param name="timeout">Timeout of completing the connection.</param>
        /// <param name="confirmCapabilitySets">The capability sets specified in Client Confirm Active PDU.
        /// This argument can be null. If it is null, then no capability set will be specified.
        /// This argument could be got from method CreateCapabilitySets.</param>

The Documentation states these fields can be null

but when I use the RDPBCGR object i instantiated and try to call this function I keep getting null reference in send pdu

I compiled this as a dll and imported to a project in vs2017 and it works I think I have access to 
what seems like all methods of the dll but I see no connection ever going out

Do I still need to instantiate objects like the channel_def struct lists etc and the capabilities or can I truly pass null to the RDPBCGR.connect(null,null,null,Timespan.minval,capabilities) function or am i doing this wrong I should at least get a connection to initiate the 23 step handshake I get most of this but something is really tripping me up can someone lend a hand?

**Comment by sweeetday** [comment]
Hi, Devcoinfet
Yes, instantiate the RdpbcgrClient and CHANNEL_DEF stuct before invoke the RDPBCGR.connect(). Please have a try with the code below and let us know if you have more issues.

RdpbcgrClient client = new RdpbcgrClient("contoso.com", "drivercomputer", "administrator", "Password01!", "192.168.0.2", 3389);

CHANNEL_DEF def = new CHANNEL_DEF();
string name = "DRDYNVC";
def.name = name;
def.options = Channel_Options.None;
client.Connect(EncryptedProtocol.NegotiationCredSsp);
client.RdpbcgrConnect(new CHANNEL_DEF[] { def }, null, null, new System.TimeSpan(20));

Thanks.
