### ISSUE TITLE
Possible Incorrect result for Smb2OverRdmaChannel_ReadWriteMultipleBufferDescriptorList

### ISSUE THREAD

**Issue by vinitagnihotri** [microsoft/WindowsProtocolTestSuites#202]
Hi,

This is a query related to SMBD - MSFT test case Smb2OverRdmaChannel_ReadWriteMultipleBufferDescriptorList

We are testing SMBD test suite for our SMBD capable server running in centos environment.

Documentation at this link for said test case
https://github.com/microsoft/WindowsProtocolTestSuites/blob/3.18.6.0/TestSuites/MS-SMBD/docs/MS-SMBD_ServerTestDesignSpecification.md

clearly indicates, "Register 4095 (ushort.MaxValue / BufferDescriptor Size, supported maximum size of BufferDescriptor List) buffers for RDMA Read."

test suite indeed sends out 4095 descriptors each having length as 2049. 
This evaluates to 4095 * 2049 = 8390655,

however test fails with following messasge

"Assert.AreEqual failed. Expected: <8388608 (0x00800000)>, Actual: 
<8390655 (0x008007FF)>. DataLength in WRITE response is 8390655"

Why MSFT would check for 838608 (this evaluates to 4094 * 2049)? Is this correct behavior?

**Comment by chenlu0616** [comment]
Hi, vinitagnihotri

The test case "Smb2OverRdmaChannel_ReadWriteMultipleBufferDescriptorList" is designed to test whether SMBD server can handle read/write over RDMA channel with multiple buffer descriptors.

Regarding to your question, the size "8388608" is calculated according to the SMBD negotiate result as the following:
     uint size = smbdAdapter.Smb2MaxReadSize;
            if (size > smbdAdapter.Smb2MaxWriteSize)
            {
                size = smbdAdapter.Smb2MaxWriteSize;
            }
So the size is the minimum value of MaxReadSize and MaxWriteSize, in this case, 8388608

From the assert failure, it looks like your server returns write count is 8390655 (4095*2049) is not the actual content size we write, the probable reason is that the last buffer size is 2 bytes instead of 2049 bytes according to the following algorithm:
     for (int index = 0, writeOffset = 0;
                index < bufferCount && writeOffset < writeContent.Length;
                ++index, writeOffset += (int)bufferLength)
            {
                int length = (int)bufferLength;
                if (length + writeOffset > writeContent.Length)
                {
                    length = writeContent.Length - writeOffset;
                }
                byte[] buffer = new byte[length];
                Array.Copy(writeContent, writeOffset, buffer, 0, length);
                smbdAdapter.SmbdWriteRegisteredBuffer(buffer, writeDescp[index]);
            }

Which means, the real content size is 4094*2049+2=8388608
Please let me know if this answers your question.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by vinitagnihotri** [comment]
I re-ran test and I could see all 4095 request are coming with 2049 as length in buffer descriptor. 
Attaching log file from our server, I have filtered it to so it shows dump of received buffer descriptors. 

Thanks & Regards,
Vinit.

[capture.log](https://github.com/microsoft/WindowsProtocolTestSuites/files/3545150/capture.log)

**Comment by vinitagnihotri** [comment]
I think I see your point, are you suggesting that we should clip write to max write size i.e. 8388608?

**Comment by chenlu0616** [comment]
Yes, I think you can have a try of that and let's see if the returned result is as expected.
Meanwhile, I will setup a windows environment to look into this issue.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by vinitagnihotri** [comment]
We clipped reads and writes to max transaction size and it seem to work. so (4094*2049)+2 seems logical result. Not sure clipping to max_r/w_size is right way to handle it or not. Since client is sending above max size should we treat this as error or clipping seems logical? If clippign is allowed then application should be able to handle difference between requested length vs returned length.

Thanks & Regards

**Comment by chenlu0616** [comment]
Hi, vinitagnihotri

When doing SMB2 Negotiation, server will return max_r/w_size in negotiate response, as defined in section "2.2.4 SMB2 NEGOTIATE Response" of [MS-SMB2], and the protocol also has mentioned the information in endnote <227> as the following:

![image](https://user-images.githubusercontent.com/18330323/63829518-56cf0600-c99c-11e9-97a7-d7308658bc5f.png)

That's where 8388608 comes from. And SMB2 has also mentioned in section "3.2.4.7 Application Requests Writing to a File or Named Pipe" as he following:

![image](https://user-images.githubusercontent.com/18330323/63834286-918a6b80-c9a7-11e9-8551-ee9257e5d5c7.png)

Seems windows use this "RemainingBytes" to indicate how many actual data will be written, which means server should check this field for data size while writing. But you are right that document does not specify clearly how will server use and verify this field. We will raise this issue and let you know if there is any update

**Comment by vinitagnihotri** [comment]
Thank you.
