### ISSUE TITLE
How can I run the tests from a ptm file without the GUI?

### ISSUE THREAD

**Issue by MattMcmullanQumulo** [microsoft/WindowsProtocolTestSuites#209]
I am attempting to set up automated validation of our SMB server against the File Server Family Test Suite. In order to do this. every command that I run on the windows client must happen over SSH. The protocol test manager GUI will not work for this purpose. Is there a way to run the tests from a given .ptm file without the GUI?

**Comment by JiajunW** [comment]
Hi Matt,

Are you going to send commands to start running test cases, from another machine to the windows client which has the test suite installed. If so, the answer is yes, you can run tests in this way. :smiley:

You can follow the guide, [Run Test Suites Remotely Using SSH](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/Run-Test-Suites-Remotely-Using-SSH). The basic idea is to create a scheduled task on the Windows client, which executes the test cases. Then you can send commands over SSH from another machine to the Windows client to start that job. And we also have a sample [shell script](https://github.com/microsoft/WindowsProtocolTestSuites/blob/3.19.9.0/RemoteRun/trigger-prototest.sh) to start testing and copy result back, you can take a look.

If you just want to run test cases from CLI in the windows client, you can use PtmCli (which is actually used in the remote run scenario). The detail usage is described [here](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/PtmCli).

Regards,
Windows Protocol Test Suites Development Team

**Comment by MattMcmullanQumulo** [comment]
This worked :)

I find it odd that PtmCli can't be run directly over SSH, but I have my test automation running now.
