### ISSUE TITLE
Issue with 3 test SMBD test cases

### ISSUE THREAD

**Issue by vinitagnihotri** [microsoft/WindowsProtocolTestSuites#210]
We are observing issue with following test cases, and all are related to test parameter "TestFileReadLargeFile"

SmbdCreditMgmt_ConsumeAllCreditServer_Timeout
SmbdCreditMgmt_ConsumeAllReceiveCredits
BVT_Smb2OverRdmaChannel_ReadLargeFile

Issue:
We are running SMBD server equivalent server in centos environment. 
While running above mentioned case, If test file specified with param: TestFileReadLargeFile (e.g TestFileReadLargeFile.txt) is of size zero, then test suite fails with error 
"Status of SMB2 Read File is STATUS_END_OF_FILE"

This is incorrect behaviour as test suite does not write anything to this file before accessing for reading. So as size of file is 0 STATUS_END_OF_FILE is valid value for read calls. 

workaround:
Above test cases passes, If said file TestFileReadLargeFile.txt is created with size 8M or more locally before executing these tests.

**Comment by vinitagnihotri** [comment]
This issue is also observed with test case "SmbdDataTransfer_ReceiveMaxReceiveSize"

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

Thanks for reporting this issue.

Just as what you mentioned, this file must be prepared before running these test cases. We will add corresponding content in configure SUT part of user guide. 

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi vinitagnihotri,

Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.

Windows Protocol Test Suites Development Team
