### ISSUE TITLE
Conflicting instructions in FileServerUserGuide.md

### ISSUE THREAD

**Issue by zherogerluo** [microsoft/WindowsProtocolTestSuites#212]
In Section 5.1.2.2.3.4 Create Symbolic Links of TestSuites/FileServer/docs/FileServerUserGuide.md, the second step in creating symlink is self-conflicting. Item 2 should be "Add a Symbolic Link to the SMBBasic folder" instead of "Add a Symbolic Link to the SMBBasic\Sub folder".

**Comment by yazeng** [comment]
Hi,

Thank you for reporting this issue. You’re right. The second step of this section is self-conflicting. 
We will fix this soon and notify you in this thread when the fix is pushed to staging branch.

Best Regards,
Yan 
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment]
Hi,

It is fixed in commit b2547f3.

Best Regards,
Yan 
Windows Protocol Test Suites Development Team

**Comment by zherogerluo** [comment]
This instruction does not seem to match the code behavior. In my actual test, the code is looking for Symboliclink2 instead of Sub/Symboliclink2. Will follow up when I confirm it, close this issue for now.
