### ISSUE TITLE
Chocolatey packages

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#217]
According to prerequisites in README to setup test stand you need to download and install at least four packages manually.

It would be better to install all required packages using package manager.
Could you provide such packages in Chocolatey?

**Comment by chenlu0616** [comment]
Hi Sergey,
 
Thanks for your good suggestion. We will take it into consideration and do some investigation later, and let you know once we have any updates.
 
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by chenlu0616** [comment]
Hi Sergey,

We have removed the dependencies in the prerequisites in newly released version [4.20.9.0](https://github.com/microsoft/WindowsProtocolTestSuites/releases/tag/4.20.9.0), and the only prerequisites you need to install is [.NET Core 3.1 SDK](https://docs.microsoft.com/en-us/dotnet/core/install/), which enables you can run the test suite on Windows/Linux/macOS.

Another option is to run our test suite with Docker, you can refer to this [guide](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/How-to-Run-Test-Suites-with-Docker) to give it a try.

Best Regards,
Windows Protocol Test Suite Team
****************************************
⭐⭐Join us at **SNIA SDC SMB IO Lab 2020 (9/21-9/23)**: https://interopevents.com/sniaonline2020

**Comment by yazeng** [comment]
Close it since it's not active for a long time.
