### ISSUE TITLE
[MS-RDPRFX] invalid channelId for blockType WBT_CONTEXT

### ISSUE THREAD

**Issue by nfedera** [microsoft/WindowsProtocolTestSuites#220]
FreeRDP was failing all MS-RDPRFX tests.
This was caused by FreeRDP's strict check of `channelId`  which, according to to [2.2.2.1.2](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/56b78b0c-6eef-40cc-b9da-96d21f197c14), must be be set to `0xFF` if the blockType is set to `WBT_CONTEXT` (`0xCCC3`).

However, `ProtoSDK/MS-RDPRFX/Server/RdprfxServer.cs` always incorrectly used `0x00`.

A PR is here https://github.com/microsoft/WindowsProtocolTestSuites/pull/219 but the azure-pipelines seem to have issues currently ;)

**Comment by huiren-jiang** [comment]
Hi Norbert,

Thanks for your contribution. 

Just as you mentioned, the value of `channelId` field used for blockType WBT_CONTEXT is inconsistent with document. Your pull request looks good and we will complete it when regression run finishes.

The reason why pipeline failed is that only user in our whitelist has permission to trigger it. We will make this clear later and trigger a new one for you.

Best Regards,

Windows Protocol Test Suites Development Team
