### ISSUE TITLE
Building PTM and Testsuites on Linux

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#221]
All components required for conformance testing of Windows Protocols are written on C#.
C# is available on Linux with [.NET](https://dotnet.microsoft.com/download). Is it possible to build and using Windows Protocol Tests on Linux without using Windows machines? Especially Windows RDP Client tests.

**Comment by lumengyanhelen** [comment]
Hi Sergey,
Yes, this is a good suggestion. We are currently exploring and investigating the solutions for Linux platforms, including re-writing the underlying libraries. We will let you know once we have any updates.
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi Sergey,

We have now upgraded our RDP client & server test suites to .NET 5 which supports Linux platforms with the recent release: https://github.com/microsoft/WindowsProtocolTestSuites/releases/tag/4.21.1.0.

Please take a look and let us know your feedback.

Best Regards,
Windows Protocol Test Suite Team

****************************************
⭐⭐Join us at **Remote Desktop Protocols IO Lab Online (1/11-1/14, 2021)**: https://interopevents.com/rdponline2021

**Comment by lumengyanhelen** [comment]
Since this thread has been inactive for a while, we will close it. Feel free to reopen if there is any further question.

Best Regards,
Windows Protocol Test Suite Team
