### ISSUE TITLE
[MS-RDPEGFX] 3.3.1.4 Bitmap Cache 0-based or 1-based indexing

### ISSUE THREAD

**Issue by nfedera** [microsoft/WindowsProtocolTestSuites#227]
[2.2.2.6 RDPGFX_SURFACE_TO_CACHE_PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/01108b9f-a888-4e5c-b790-42d5c5985998) and [2.2.2.7 RDPGFX_CACHE_TO_SURFACE_PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/78c00bcd-f5cb-4c33-8d6c-f4cd50facfab) define cacheSlot like this:

> **cacheSlot (2 bytes):** A 16-bit unsigned integer that specifies **the index** of the bitmap cache entry in which the source bitmap data MUST be stored. 
> The value of this field is constrained as specified in section [3.3.1.4](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/d1c1540f-9bc7-4344-81e0-3cce6b845f86).

And here is what [[MS-RDPEGFX] 3.3.1.4 Bitmap Cache](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/d1c1540f-9bc7-4344-81e0-3cce6b845f86) tells us about the size and indexing of the cache slots:
> - Each bitmap is associated with a key and is stored in a variable-length slot (**identified by a slot index**)
> - The maximum possible **number** of variable-length slots is 25,600 in the case of a 100 MB cache and 4,096 in the case of a 16 MB cache. 

With common zero-based numbering the maximum cacheSlot index would be 25599 and 4095 in the case of a 16 MB cache. 

But [RdpegfxTestSuite.cs](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/RdpegfxTestSuite.cs) defines these values like this ...
```C#
public static ushort maxCacheSlot = 25600;
public static ushort maxCacheSlotForSmallCache = 4096;
```
... and [RdpegfxSurfaceToCacheToSurfaceTest.cs](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/RdpegfxSurfaceToCacheToSurfaceTest.cs) uses these values in the PDU.

This seems to imply that the test suite expects the client to use a 1-based numbering system here.

This is hardened by the fact that mstsc aborts with a protocol error message if a `cacheSlot` value of `0` is used in the RDPGFX_SURFACE_TO_CACHE_PDU.

However, I don't see any reference to 1-based indexing in the specs.

Can you please confirm that 1-based indexing is really expected and point me to the respective documentation, if it exists?

Thanks!

**Comment by huiren-jiang** [comment]
Hi Norbert,

Thanks for your reporting this issue. 

We have started to work on this. When there is update, we will notify you in this thread.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by nfedera** [comment]
Thanks for the confirmation!
