### ISSUE TITLE
Running multiple instance of Protocol Test Manager

### ISSUE THREAD

**Issue by visual901** [microsoft/WindowsProtocolTestSuites#235]
Hello,
I am trying to run the Protocol Test Manager in multiple instance, either in GUI or CLI but it doesn't allow that.
When 1 suite is running and I try to run another in a different process I get this message:
"Protocol Test Manager or PtmCli is already running."

What I'm trying to do is use Python to run the test suite against multiple servers at once (from the same client).

Do you have any ideas how can this be achieved?
Thanks

**Comment by chenlu0616** [comment]
Hi visual901,

Thanks for reporting this issue. In order to find out a better solution could you give us some context like:
1.	Which test suite you are running?
2.	Will the multiple instances share with the same configuration files (ptfconfig file)?
3.	Will the multiple instances run with the same test cases or with different test cases categories?
4.	When you mention “multiple servers”, do you mean that you want each one instance run against with one specific server?

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by visual901** [comment]
Hello
1. I'm trying to run the File Server Protocol Family Server Test Suite.
For testing a SMB server (Microsoft and non Microsoft servers.)

2. The multiple instance don't share the exact same PTM file (which means different ptfconfig as well), but instead have a copy of the PTM file with a different SUTIpAddress set.

3. The multiple instances run the same test cases, only the SutIpAddress and SutComputerName (and maybe other common fields such as shares) fields are different.

4. Yes. So instance X would run against server 192.111.111.111 and instance Y will run against 192.111.111.112 for example.
Although it's possible that we will want to have 2 instances be run against the same server but to different shares on that server, at the same time.

The thing is the Protocol Test Manager doesn't even start a new instance of itself, so long as it detects that it's already running (so it's impossible to open 2 windows of it - GUI and impossible to run PtmCli.exe when it's already running in another terminal - CLI).

Thanks!

**Comment by chenlu0616** [comment]
Hi visual901,
 
Thanks for clarifying your scenario. 
 
Currently PTM does not support running multiple instances on the same client by GUI or CLI. However, based on the requirements, we plan to support this feature in the near future. You can watch our repository to get the notification as soon as the feature is released.
 
If you still want to run multiple instances against different SUT with different IPs, the easiest way is to use vstest.console.exe loading test binaries directly and assigning test setting files separately. You can copy the bin folder (which includes all the binaries and ptfconfig files, as well as testrunconfig file. Normally it’s under the location “C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\3.20.1.0\Bin” after test suites installed) to a separate location, under which you can modify the ptfconfig files, and then run vstest from the location separately, the command is like the following: (Here we use Visual Studio 2017 Community version): 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Common Extensions\Microsoft\TestWindow>vstest.console.exe "C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\3.20.1.0\Bin\MS-SMB2_ServerTestSuite.dll" /Settings:"C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\3.20.1.0\Bin\ServerLocalTestRun.testrunconfig"

![image](https://user-images.githubusercontent.com/18330323/89618074-ffc8f500-d8bd-11ea-92aa-058a4632406e.png)


Best Regards,
Windows Protocol Test Suite Team
****************************************
⭐⭐Join us at **SNIA SDC SMB IO Lab 2020 (9/21-9/23)**: [https://interopevents.com/sniaonline2020](url)

**Comment by chenlu0616** [comment]
Hi visual901,

We are glad to inform you that PTMCli supports running multiple instances in the newly released version [4.20.9.0](https://github.com/microsoft/WindowsProtocolTestSuites/releases). You can follow this [guide](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/PtmCli) to have a try.

Please be noticed that:
1. Currently only PTMCli supports running multiple instances by assigning ptm profile, PTM GUI does not support.
2. To use the multiple instance feature of PTMCli, you have to adopt the latest test suite [4.20.9.0](https://github.com/microsoft/WindowsProtocolTestSuites/releases) and re-generate ptm profile for it, the previous test suite version is not applied.

Best Regards,
Windows Protocol Test Suite Team
****************************************
⭐⭐Join us at **SNIA SDC SMB IO Lab 2020 (9/21-9/23)**: https://interopevents.com/sniaonline2020

**Comment by yazeng** [comment]
Close it since it's not active for a long time.
