### ISSUE TITLE
DFS tests for standalone only support

### ISSUE THREAD

**Issue by pdonette** [microsoft/WindowsProtocolTestSuites#243]
Hi,

The test suite was configured for standalone tests only.
However, the tests  DomainReferralV4EXSiteToDC, DomainReferralV4EXToDC, DomainReferralV2ToDC, DomainReferralV1ToDC and BVT_DomainReferralV3ToDC Fail in error as follows:

2021-06-11 15:35:31.874 [TestStep] Verify server response.
2021-06-11 15:35:31.875 [CheckFailed] Assert.AreEqual failed. Expected: <0 (0x00000000)>, Actual: <3221225485 (0xC000000D)>. Expected Domain Referral v3 to DC Response is STATUS_SUCCESS, but real status isSTATUS_INVALID_PARAMETER
2021-06-11 15:35:31.875 [Comment] at Microsoft.Protocols.TestSuites.FileSharing.DFSC.TestSuite.DomainReferralToDC.BVT_DomainReferralV3ToDC() in D:\a\1\s\TestSuites\FileServer\src\DFSC\TestSuite\DomainReferralToDC.cs:line 48
2021-06-11 15:35:31.887 [TestFailed] Microsoft.Protocols.TestSuites.FileSharing.DFSC.TestSuite.DomainReferralToDC.BVT_DomainReferralV3ToDC
I think these tests should be considered as inconclusive.
See Attached files : 
[RootAndLinkReferralStandaloneV2ToDFSServer.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/6649683/RootAndLinkReferralStandaloneV2ToDFSServer.zip)

Please clarify.

Thanks,
Pascal.

**Comment by chenlu0616** [comment]
Hi Pascal,
Thanks for your question, I checked the attached https://github.com/microsoft/WindowsProtocolTestSuites/files/6649683/RootAndLinkReferralStandaloneV2ToDFSServer.zip file and found that the included test log in this folder is showing as the following error message:
 
![image](https://user-images.githubusercontent.com/18330323/122572367-42339480-d080-11eb-81ef-070b78648417.png)


And the error code is different with the error in the description:
[CheckFailed] Assert.AreEqual failed. Expected: <0 (0x00000000)>, Actual: <3221225485 (0xC000000D)>. Expected Domain Referral v3 to DC Response is STATUS_SUCCESS, but real status is STATUS_INVALID_PARAMETER

Could you confirm which is the issue you think should make the tests be inconclusive and share the corresponding details log?

Thanks.
 
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by pdonette** [comment]
I re ran the tests again which show all the tests in failure that should be considered as inconclusive when the DFSC test suite is configured for Standalone support only.
[2021-06-18-15-41-06.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/6678068/2021-06-18-15-41-06.zip)

Thanks.

**Comment by chenlu0616** [comment]
Hi Pascal,
Thanks for the updates.

I think you are right that we should make these test cases run into inconclusive while testing against standalone environment, we will follow up this issue and update the test code to fix it.
 
Thanks.
 
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by chenlu0616** [comment]
Hi Pascal,

This issue has been fixed and the code has been merged into main branch already, feel free to clone the code and build to execute the test cases.
 
Thanks.
 
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi Pascal,

We will close this thread for now, as it has been inactive for some time. Feel free to reopen it or create new issue if you have any questions.

Thanks,
Windows Protocol Test Suites Development Team
