### ISSUE TITLE
SMB2_CREATE error handling for invalid pathname

### ISSUE THREAD

**Issue by pdonette** [microsoft/WindowsProtocolTestSuites#245]
The MS-SMB2.pdf specification says now the following:

3.3.5.9 Receiving an SMB2 CREATE Request
If the file name in the Buffer field of the request fails to resolve the pathname components as specified in [MS-FSCC] section 2.1.5.1, the server SHOULD<277> fail the request with STATUS_INVALID_PARAMETER.

The STATUS_OBJECT_NAME_INVALID error code is no longer mentioned for SMB2_CREATE operation.

However, the CreateCloseTestCaseS525 test case for FileServer test version 4.21.5.0 still refers to the old version of the document:
2021-06-11 14:58:56.696 [Checkpoint] "[MS-SMB2] 3.3.5.9: If the file name fails to conform with the specification of a relative pathname in [MS-FSCC] section 2.1.5, the server MUST fail the request with STATUS_OBJECT_NAME_INVALID.

Could please clarify?

Thanks,
Pascal

**Comment by MaggieWang0** [comment]
Hi Pascal,

We are currently investigating the issue and follow up with EE team. We will get back to you later.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by MaggieWang0** [comment]
Hi Pascal,

Since this thread has been inactive for a long time, we will close it for now. Please feel free to reopen if the issue still exists.

Best Regards,
Windows Protocol Test Suites Development Team
