### ISSUE TITLE
Hp 430 notebook Laptop with Window 7 platinum 32-bit showing error.

### ISSUE THREAD

**Issue by AkramMikrani** [microsoft/WindowsProtocolTestSuites#248]
error showing the process could not be started because the configured identity is incorrect. Check the username and password.

**Comment by Dingshouqing** [comment]
Hi AkramMikrani,
Thanks for contacting us, is there any issue when you run our TestSuite or our PTM tool? If so could you please provide the log or network capture to us to do further investigation?

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi AkramMikrani,

We will close this thread for now, as it has been inactive for some time. Feel free to reopen it if you still have any questions.

Thanks,
Windows Protocol Test Suites Development Team
