### ISSUE TITLE
Trojan:MSIL/AgentTesla.SMK!MTB Virus detected in FileServer-TestSuite-ServerEP.zip v4.21.9.0

### ISSUE THREAD

**Issue by visual901** [microsoft/WindowsProtocolTestSuites#251]
I've downloaded the FileServer-TestSuite-ServerEP.zip from https://github.com/microsoft/WindowsProtocolTestSuites/releases

https://github.com/microsoft/WindowsProtocolTestSuites/releases/download/4.21.9.0/FileServer-TestSuite-ServerEP.zip

And I am getting a virus detection with Windows Security:
Trojan:MSIL/AgentTesla.SMK!MTB

**Comment by visual901** [comment]
Tested again today, and I dont get a virus alert anymore in Windows.
In Virustotal.com there's 1 engine that detected a trojan:
Trojan/Generic.ASMalwS.34B68C7

https://www.virustotal.com/gui/file/99700a070aad534c2f3df7a6b2ecad9dad2835d4ef6efbbf32f4cd2995c73480/detection

**Comment by lumengyanhelen** [comment]
Hi visual901,

Thanks for contacting us. Please feel free to let us know if you need further assistance on this.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by Dingshouqing** [comment]
Hi visual901,

Since this thread has been inactive for some time, we will close it for now. Please feel free to contact us if there is any further question.

Best Regards,
Windows Protocol Test Suites Development Team
