### ISSUE TITLE
Test host process crashed : No usable version of libssl was found

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#252]
After compiling the FileServer test suite according to the instructions here for MacOS (11.6.2),
running the test ends with the error below and a dotnet crash window (SIGABRT):

```
The active test run was aborted. Reason: Test host process crashed : No usable version of libssl was found

Test Run Aborted.

```
Apparently dotnet needs a different version of libssl or something?
Can anyone provide updated build instructions to fix this?

Thanks!

**Comment by gwr** [comment]
Looks like this might be relevant.
https://github.com/dotnet/runtime/issues/46071

**Comment by Dingshouqing** [comment]
Hi Gordon,

Thanks for contacting us.

This is a .NET runtime dependencies issue. Our test suite code used AES-CCM and AES-GCM cryptographic in .NET 5  while doing the negotiation and encryption/description, but currently on macOS, the system libraries don't support AES-CCM or AES-GCM for third-party code, so the AesCcm and AesGcm classes use OpenSSL for support, for more details please refer to this document: [Cross-platform cryptography in .NET Core and .NET 5 | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography)

![3](https://user-images.githubusercontent.com/17266569/148872513-2ef8271d-545d-4fad-8770-2e5ebfcf51d2.png)

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by gwr** [comment]
Thanks, I was able to work-around this problem by installing OpenSSL locally on MacOS via
```
brew install openssl@1.1
```
and then making shared library links under /usr/local/lib
and then adding these environment settings to
TestSuites/FileServer/build.sh
```

export PATH=/usr/local/opt/openssl@1.1/bin:/usr/local/bin:$PATH
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
export DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib:$DYLD_LIBRARY_PATH"
```
It might help to add this to the "how to build" documentation in the
top-level README.md or perhaps on the Wiki.

Thanks.
