### ISSUE TITLE
Algorithm_NotingFileModified_Dir_LastAccessTime could be improved

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#257]
I'm running these tests against a non-Windows platform (OTHERFS)
and noticed Algorithm_NotingFileModified_Dir_LastAccessTime failing.
FSA/TestSuite/CommonAlgorithm/Algorithm_Noting_FileModified.c
The reason it fails is that on some systems (including ours) the
access time is not updated unless you actually read data.
This test only opens the file for read, but does not read.

I could use some help figuring out how to add code to make this test
read from the file before checking that access time.

**Comment by Dingshouqing** [comment]
Hi Gordon,

Thanks for reporting this issue, We'll update our code to try to read the data before checking the access time. This may need some time and we will notify you once it is done.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by michaelnwanna** [comment]
Hi Gordon,

The reported issue has been resolved. Please try it again and let us know the outcome.

Warm Regards.
