### ISSUE TITLE
Want to run AlternateDataStream tests on OTHERFS

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#258]
This is an enhancement request.  I'd like to be able to run all the AlternateDataStream
test cases on OTHERFS, but today they only run for NTFS.

I don't see how to do this properly, so I've just
commented out the check that made these NTFS-only

I welcome advice on a better solution.  Thanks!

From 5a56f1da1c57da76844ad13e2318018d181de210 Mon Sep 17 00:00:00 2001
From: Gordon Ross <gwr@racktopsystems.com>
Date: Sat, 15 Jan 2022 08:02:53 -0500
Subject: [PATCH 5/5] Want to run AlternateDataStream tests on OTHERFS

---
 .../AlternateDataStream/AlternateDataStreamTestCases.cs         | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/TestSuites/FileServer/src/FSA/TestSuite/AlternateDataStream/AlternateDataStreamTestCases.cs b/TestSuites/FileServer/src/FSA/TestSuite/AlternateDataStream/AlternateDataStreamTestCases.cs
index 1ad6214e..e18454f8 100644
--- a/TestSuites/FileServer/src/FSA/TestSuite/AlternateDataStream/AlternateDataStreamTestCases.cs
+++ b/TestSuites/FileServer/src/FSA/TestSuite/AlternateDataStream/AlternateDataStreamTestCases.cs
@@ -54,7 +54,7 @@ namespace Microsoft.Protocols.TestSuites.FileSharing.FSA.TestSuite
             BaseTestSite.Log.Add(LogEntryKind.Comment, "\t 2. Transport: " + this.fsaAdapter.Transport.ToString());
             BaseTestSite.Log.Add(LogEntryKind.Comment, "\t 3. Share Path: " + this.fsaAdapter.UncSharePath);
 
-            BaseTestSite.Assume.AreEqual(FileSystem.NTFS, this.fsaAdapter.FileSystem, "Alternate Data Stream is only supported by NTFS file system.");
+//            BaseTestSite.Assume.AreEqual(FileSystem.NTFS, this.fsaAdapter.FileSystem, "Alternate Data Stream is only supported by NTFS file system.");
 
             this.fsaAdapter.FsaInitial();
 
-- 
2.32.0 (Apple Git-132)

**Comment by Dingshouqing** [comment]
Hi Gordon,

We’ll update our code and add a new property in “MS-FSA_ServerTestSuite.deployment.ptfconfig” file as below
```
<Property name="WhichFileSystemSupport_AlternateDataStream" value="NTFS;REFS;UDFS" />
```
If OTHERFS supports AlternateDataStream then you could update as below:
```
< Property name="WhichFileSystemSupport_AlternateDataStream" value="NTFS;REFS;UDFS; OTHERFS" />
```
Then our code will support to run AlternateDataStream tests on OTHERFS

We will keep you updated once it is done.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by Dingshouqing** [comment]
Hi Gordon,

We did update our code and now it supports running AlternateDataStream tests by configured file system by commit [3a58e75](https://github.com/microsoft/WindowsProtocolTestSuites/commit/3a58e7577fe7eee5ffdb32ac2ade6f547324f693).
You could clone our latest code, build a new package, add OTHERFS to the value of WhichFileSystemSupport_AlternateDataStream as below, and run tests again
```
<Property name="WhichFileSystemSupport_AlternateDataStream" value="NTFS;REFS;OTHERFS;" />
```

Best Regards,
Windows Protocol Test Suites Development Team
[⭐⭐Join us at SNIA EMEA SDC SMB3 IO Lab 2022 (4/5-4/7)](https://interopevents.com/en-us/snia2022)

**Comment by Dingshouqing** [comment]
Hi Gordon,

Since this thread has been inactive for some time, we will close it for now. Please feel free to contact us if there is any further question.

Best Regards,
Windows Protocol Test Suites Development Team
