### ISSUE TITLE
MS-WSP: CPMConnectIn request appears to be corrupt

### ISSUE THREAD

**Issue by liranoz12** [microsoft/WindowsProtocolTestSuites#271]
Hi,

[MS-WSP] _CPMConnectIn_  request appears to be corrupt.
 _Wireshark_ is unable to parse it properly, because of the following assertion : 

`[Dissector bug, protocol MS-WSP: ../epan/dissectors/packet-mswsp.c:4476: failed assertion "offset - offset_in == (int)size"]
`
I suspect that PropertySet2 was not initialized correctly. 

Tests are running using a docket, image was downloaded from : 
https://hub.docker.com/_/microsoft-windowsprotocoltestsuites

pcap attached : 
[tcpdump_windows_server.pcap.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/8706880/tcpdump_windows_server.pcap.zip)

Thanks!

**Comment by Dingshouqing** [comment]
Hi Liran,
Thanks for reporting this issue.

From your capture, it looks like it’s a Wireshark parser bug, according to our document [[MS-WSP]: CBaseStorageVariant | Microsoft Docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsp/ff5bda0c-cb69-4c8c-b3a4-8f0afda49f84) VT_LPWSTR is a structure and it has two elements cLen and string as below:
![1](https://user-images.githubusercontent.com/17266569/169230234-a47b5175-6f11-45f8-8b47-eeed214e932d.png)

But it seems Wireshark parses this structure as a null-terminated string, which causes parsing to fail.
The right binary data of vValue should be: 01 00 00 00  00 00 00 00, cLen is 0, as value is 0x00000000 so there is no string element.
![2](https://user-images.githubusercontent.com/17266569/169230360-9987b27d-729c-4436-af86-51dd1d68a5b8.png)

“a5 ac af xxx” belongs to the next PropertySet.   
![3](https://user-images.githubusercontent.com/17266569/169230410-cfa56a3e-a2e2-4972-9193-3e6b918380c6.png)

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by liranoz12** [comment]
Great, thanks for the help!
