### ISSUE TITLE
Could test SMB2 setinfo BASIC with time = -2

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#297]
I see that Windows 11 will occasionally call SMB2_SetInfo  with Class=FILE_INFO and InfoLevel SMB2_FILE_BASIC_INFO, where the LastAccessTime field is -2

[MS-FSCC] section 2.4.7 describes this, though I found the footnote easier to read:

> <98> Section 2.4.7: The file system updates the values of the LastAccessTime, LastWriteTime, and ChangeTime members as appropriate after an I/O operation is performed on a file. However, a driver or application can request that the file system not update one or more of these members for I/O operations that are performed on the caller's file handle by setting the appropriate members to -1. A driver or application can subsequently request that the file system resume updating one or more of these members for I/O operations that are performed on the caller's file handle by setting the appropriate members to -2. The caller can set one, all, or any other combination of these three members to -1 and/or -2. Only the members that are set to -1 will be unaffected by I/O operations on the file handle; the other members will be updated as appropriate. This behavior is consistent across all file system types. Note that even though -1 and -2 can be used with the CreationTime field, they have no effect because file creation time is never updated in response to file system calls such as read and write.

In summary, both -1 and -2 are "special", and the behavior of LastAccessTime and LastWriteTime could be verified with tests that set value -1, then do some I/O, check that the times don't change; set -2, do some I/O and verify that the times resume changing after I/O.

**Comment by obaro** [comment]
Hi @gwr,

We've got tests for setting File Information to **-1** ([FileInfo_Set_FileBasicInformation_Timestamp_MinusOne.cs](https://github.com/microsoft/WindowsProtocolTestSuites/blob/main/TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_MinusOne.cs)), **-2** ([FileInfo_Set_FileBasicInformation_Timestamp_MinusTwo.cs](https://github.com/microsoft/WindowsProtocolTestSuites/blob/main/TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_MinusTwo.cs)) and **0** [FileInfo_Set_FileBasicInformation_Timestamp_Zero.cs](https://github.com/microsoft/WindowsProtocolTestSuites/blob/main/TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_Zero.cs)), and they include setting the LastAccessTime.

Can you confirm that these match what you're looking for?

**Comment by obaro** [comment]
Thanks for the confirmation.
