### ISSUE TITLE
Timestamp MinusTwo tests are in BVT but others are not

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#304]
Three new timestamp test files were added in:
PR 7874493: Add 0, -1, -2 timestamps test case and TDS
TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_Zero.cs
TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_MinusOne.cs
TestSuites/FileServer/src/FSA/TestSuite/FileInformation/FileInfo_Set_FileBasicInformation_Timestamp_MinusTwo.cs

We like to run the BVT category tests, and noticed that only the MinusTwo tests run as part of BVT, not the others.
Was that an oversight?  Would it make sense to run all three as part of category BVT?

I also notice that many of these tests are enabled based on logic like:
``` 
            if (this.fsaAdapter.FileSystem != FileSystem.NTFS && this.fsaAdapter.FileSystem != FileSystem.REFS)
            {
                 this.TestSite.Assume.Inconclusive(" blah blah ");
             }
```
It might be better to have new xxxSupported settings for this instead? eg.
If (this.fsaAdapter.IsSetFileTimestampSupported) ...
or something like that?   Perhaps ptfconfig settings like this:
```
// Does the file system handle setting the "special" time values 0, -1, -2?
// Configured separately for files vs. directories.
 WhichFileSystemSupport_SetFileTimeSpecial = "NTFS;REFS";
 WhichFileSystemSupport_SetDirTimeSpecial = "NTFS;REFS;"
```
In our local change we would add ";OTHERFS" to the above.

Thanks.

**Comment by obaro** [comment]
Hi @gwr.
Thanks for your suggestions on the settings. That seems like a good ask, and we'll review and share updates with you.
Regarding the BVT category, it appears to be an oversight. I'll verify and revert.

**Comment by obaro** [comment]
@gwr This issue has been addressed in the commit (https://github.com/microsoft/WindowsProtocolTestSuites/commit/4e91a49f9c8b2982870b55599a2d6a9224975dd5). The BVT category has been expanded to include MinusOne and Zero
