### ISSUE TITLE
build all fails on windows 8

### ISSUE THREAD

**Issue by mpardhi** [Microsoft/WindowsProtocolTestSuites#42]
Hi All,

Windows Protocol Test Suite buildall.cmd  fails  on windows 8.1.

I got below error messages after running buildall.cmd , attached complete log with this.
also please let me know if there is any additional step required to install/compile it on windows 8.1 .

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva- /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\Common\Adapter\bin\Debug\CommonAdapter.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Protocol Test Framework\bin\Microsoft.Protocols.TestTools.dll" /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\Common\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-DFSC\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Dfsc.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\FileAccessService\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.FileAccessService.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-FSRVP\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Fsrvp.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-SMB\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-SMB2\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-RPCE\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.Networking.Rpce.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-NLMP\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.Security.Nlmp.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\Sspi\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.Security.Sspi.dll /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\ProtoSDK\MS-SWN\bin\Debug\Microsoft.Protocols.TestTools.StackSdk.Swn.dll /reference:"C:\Program Files (x86)\Protocol Test Framework\bin\Microsoft.Protocols.TestTools.VSTS.dll" /reference:"C:\Program Files (x86)\Common Files\microsoft shared\Spec Explorer 2010\2.2.0.0\Microsoft.SpecExplorer.Runtime.dll" /reference:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ReferenceAssemblies\v4.0\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll" /reference:"C:\Program Files (x86)\Common Files\microsoft shared\Spec Explorer 2010\2.2.0.0\Microsoft.Xrt.Runtime.dll" /reference:D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\Adapter\bin\Debug\MS-SMB2Model_ServerAdapter.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\MS-SMB2Model_ServerTestSuite.dll /target:library /utf8output AppInstanceIdTestCase.cs BreakReadHandleLeaseV1TestCase.cs BreakReadHandleLeaseV2TestCase.cs BreakReadLeaseV1TestCase.cs BreakReadLeaseV2TestCase.cs BreakReadWriteHandleLeaseV1TestCase.cs BreakReadWriteHandleLeaseV2TestCase.cs BreakReadWriteLeaseV1TestCase.cs BreakReadWriteLeaseV2TestCase.cs ConflictTestCase.cs CreateCloseTestCase.cs CreditMgmtTestCase.cs DurableHandleV1PreparedWithBatchOplockReconnectTestCase.cs DurableHandleV1PreparedWithLeaseV1ReconnectTestCase.cs DurableHandleV2PreparedWithBatchOplockReconnectTestCase.cs DurableHandleV2PreparedWithLeaseV1ReconnectTestCase.cs DurableHandleV2PreparedWithLeaseV2ReconnectTestCase.cs EncryptionTestCase.cs LeaseOplockTestCase.cs NegotiateTestCase.cs OplockLeaseTestCase.cs OplockOnShareWithForceLevel2AndSOFSTestCase.cs OplockOnShareWithForceLevel2WithoutSOFSTestCase.cs OplockOnShareWithoutForceLevel2OrSOFSTestCase.cs OplockOnShareWithoutForceLevel2WithSOFSTestCase.cs PersistentHandleReconnectTestCase.cs ReplayCreateDurableHandleV1TestCase.cs ReplayCreateDurableHandleV2PersistentTestCase.cs ReplayCreateDurableHandleV2TestCase.cs ReplayCreateNormalHandleTestCase.cs ReplayCreateWithoutHandleTestCase.cs ReplayFileOperationTestCase.cs RequestDurableHandleV1BatchOplockTestCase.cs RequestDurableHandleV1LeaseV1TestCase.cs RequestDurableHandleV2BatchOplockTestCase.cs RequestDurableHandleV2LeaseV1TestCase.cs RequestDurableHandleV2LeaseV2TestCase.cs RequestPersistentHandleTestCase.cs ResilientHandleBasicTestCase.cs ResilientHandleDurableTestCase.cs SessionMgmtBindSessionAfterDisconnectionScenarioTestCase.cs SessionMgmtBindSessionAfterLogOffScenarioTestCase.cs SessionMgmtBindSessionScenarioTestCase.cs SessionMgmtNewSessionScenarioTestCase.cs SessionMgmtReconnectSessionScenarioTestCase.cs SigningTestCase.cs TreeMgmtTestCase.cs ValidateNegotiateInfoTestCase.cs "C:\Users\mangesh.pardhi\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
AppInstanceIdTestCase.cs(25,50): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadHandleLeaseV1TestCase.cs(25,59): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadHandleLeaseV2TestCase.cs(25,59): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadLeaseV1TestCase.cs(25,53): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadLeaseV2TestCase.cs(25,53): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadWriteHandleLeaseV1TestCase.cs(25,64): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadWriteHandleLeaseV2TestCase.cs(25,64): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadWriteLeaseV1TestCase.cs(25,58): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
BreakReadWriteLeaseV2TestCase.cs(25,58): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
ConflictTestCase.cs(25,45): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
CreateCloseTestCase.cs(25,48): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
CreditMgmtTestCase.cs(25,47): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
DurableHandleV1PreparedWithBatchOplockReconnectTestCase.cs(25,84): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
DurableHandleV1PreparedWithLeaseV1ReconnectTestCase.cs(25,80): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
DurableHandleV2PreparedWithBatchOplockReconnectTestCase.cs(25,84): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
DurableHandleV2PreparedWithLeaseV1ReconnectTestCase.cs(25,80): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
DurableHandleV2PreparedWithLeaseV2ReconnectTestCase.cs(25,80): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
EncryptionTestCase.cs(25,47): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
LeaseOplockTestCase.cs(25,48): error CS0246: The type or namespace name 'PtfTestClassBase' could not be found (are you missing a using directive or an assembly reference?) [D:\PrimaryData\Setups\software-microsoftinstaller\WindowsProtocolTestSuites\TestSuites\FileServer\src\SMB2Model\TestSuite\MS-SMB2Model_ServerTestSuite.csproj]
NegotiateTestCase.cs(25,46): error CS0246
[out.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/248591/out.zip)

**Comment by yazeng** [comment]
Hi,
Some of the test suites (FileServer and SMB) are using model-based testing. In order to build them, you should build the PTF (protocol test framework) by option "formodel" and install the built ProtocolTestFrameworkInstaller.msi. 
I assume that you have already installed the PTF which is not built by option "formodel". Then you need to uninstall it, reinstall the newly built one, and try again.

Thanks,
Yan

**Comment by mpardhi** [comment]
Thanks Yan for your Quick reply, 

Here are the steps i have followed before running   buildall.cmd
1)installed all the dependencies.(.Net framework ,Wix toolset ,visual studio etc)
2)build PTF using option formodel.
3)buildall from MSFT suite.
still getting the same error .....

I have one question do i need to perform any-kind of setting before building PTF with foremodel option.or after installation of PTF before running MSFT suite.

Thanks,
Mangesh p

**Comment by yazeng** [comment]
Hi Mangesh,

I'm still wondering if you installed the correct PTF version.
I updated Readme of PTF recently as below, could you check it again? 
https://github.com/Microsoft/protocoltestframework

To build PTF by formodel option, you must install Spec Explorer.
If Spec Explorer is not installed, then build PTF by formodel should fail.
And make sure you install PTF before you build test suites.

And no other settings are needed.

Thanks,
Yan

**Comment by yazeng** [comment]
Hi Mangesh,
I just found that build.cmd of PTF didn't clean the old binaries. That might be the reason of this issue. If you built PTF without "formodel" option, and rebuilt it with "formodel" option, it will still generate an "old" msi file since the old binaries were not cleared.
I've updated the build script of PTF. Could you use the latest PTF code and try again?

Thanks,
Yan

**Comment by mpardhi** [comment]
Thanks Yan,

I will try it and let you know if i face any problem.

Thanks,
Mangesh P

**Comment by yazeng** [comment]
Close it since no responses for more than two months.
