### ISSUE TITLE
Version of .net framework needed.

### ISSUE THREAD

**Issue by ahmedha** [Microsoft/WindowsProtocolTestSuites#61]
Hello,

The prerequisite section states that one needs to install ".Net framework 3.5", however, there was some confusion at the Widows Plugfest if a higher version is good enough?  Can you please confirm?

I will be running/extending the following protocol test sutie:
File Server Family Test Suite  :   [MS-SMB2], [MS-FSRVP], [MS-RSVD]

Thank you,
Ahmed.

**Comment by yazeng** [comment]
Hi Ahmed,
For File Server test suite, higher version is good enough. You can just install .Net framework 4.5.
I will check the requirement of other test suites and update it in Readme.

Thanks,
Yan

**Comment by ahmedha** [comment]
Thank you.
Ahmed.

**Comment by yazeng** [comment]
Readme is updated. Close this issue.
