### ISSUE TITLE
Save a test profile

### ISSUE THREAD

**Issue by ahmedha** [Microsoft/WindowsProtocolTestSuites#63]
Hello,

How do I save a test profile?  I noticed there is a way to upload a test profile, but don't see a "button" to save a profile.

Thank you,
Ahmed.

**Comment by yazeng** [comment]
It's in the "Run selected test cases" page, press "Export/Import" button, you will see "Save Profile".
![saveprofile](https://cloud.githubusercontent.com/assets/10937464/16509588/244fce20-3f71-11e6-98fd-256ea5954c1f.png)

**Comment by ahmedha** [comment]
Thank you,
Ahmed.
