### ISSUE TITLE
[Kerberos] Setting up a Samba AD DC

### ISSUE THREAD

**Issue by cryptomilk** [Microsoft/WindowsProtocolTestSuites#86]
Hello,

I'm currently at the Samba IO Lab and created some scripts to provision and prepare DC01 for the Kerberos Testsuite using Samba AD.

I've created a repository where I will try to keep them up to date. You can find them here.

https://github.com/gladiac/Samba-WindowsProtocolTestsuites

Note that they are not complete yet and we will work on simplifying them. Should we add a note to the documentation?

I'm opening a bug so there is some record of the scripts at least.

**Comment by abartlet** [comment]
Thanks Andreas.  The other way to approach this would be for the PowerShell scripts to be run not on the SUT, but on the test driver.  That way they stop being implementation-specific.

**Comment by yazeng** [comment]
Thanks Andreas and Andrew. It's really a good feedback.
We filed a bug to track this.

**Comment by JiajunW** [comment]
The script (WindowsProtocolTestSuites/TestSuites/Kerberos/Setup/Scripts/Configure-UsersAndComputers.ps1) is currently run on the driver machine. Furthermore, we use ldif file to add computers and users now. It should be implementation-unaware.
