### ISSUE TITLE
ADFamily LDAP tests assuming connection between netbios and DNS domain name

### ISSUE THREAD

**Issue by abartlet** [Microsoft/WindowsProtocolTestSuites#87]
In AD, the NetBIOS name of a domain may be totally unconnected with the DNS name of the domain.

The test suites assumes that there is a link between PrimaryDomain.DNSName and the NetBIOS name sent to SSPI in AdLdapClient.cs (line 488 in the copy we had)

**Comment by abartlet** [comment]
As well as the SASL binds, simple binds need a similar fix

**Comment by dongruiqing** [comment]
@abartlet This issue has been fixed. Please take a look. Thanks.

**Comment by yazeng** [comment]
Close this issue since no update for a long time.
