### ISSUE TITLE
ADFamily LDAP does not honour isWindows

### ISSUE THREAD

**Issue by abartlet** [Microsoft/WindowsProtocolTestSuites#88]
The isWindows flag is not consistently honoured in the LDAP test suite of ADFamily, specifically in the cleanup code of the LDAP model adaptor (AD_LDAPModelAdapter.cs)

This is used to check error codes - LDAP error codes are supplemented by a windows error code in the error string on windows, and the test is asserting this in all cases.

**Comment by yazeng** [comment]
Thanks for the feedback. The bug was filed and will be fixed when AD family test suite is open source.

Yan

**Comment by JiajunW** [comment]
This should be fixed in the latest code. Feel free to reopen it if the problem still exists.
