### ISSUE TITLE
The InstallPrerequisites script should include cases for ADFamily etc

### ISSUE THREAD

**Issue by abartlet** [Microsoft/WindowsProtocolTestSuites#89]
It would be very helpful if the InstallPrerequisites script included cases for all the testsuites included in the releases page, not just those that are currently open source.

This will help in automatically installing all the test suites, because this script knows the simple download locations and silent install scripts.

**Comment by yazeng** [comment]
Thanks for the feedback. We will update the script when we open source ADFamily.

**Comment by JiajunW** [comment]
The latest version of InstallPrerequisites script supports all our test suites now.
