### ISSUE TITLE
How to get File Server Test Suite VMs

### ISSUE THREAD

**Issue by VivianTian** [Microsoft/WindowsProtocolTestSuites#93]
The issue is filed for one of our partners.
The question is:
In the past, we have got MSFT test suite enabled on VMs that have been handed to us. I was wondering if you have something of that sort that we could use for this purpose.

**Comment by VivianTian** [comment]
Have you tried to setup a VM by yourself? You can follow the user guide on GitHub https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/FileServer/docs/FileServerUserGuide.md. 
We can help answer your further questions if any.

**Comment by abartlet** [comment]
On Thu, 2016-10-27 at 19:59 -0700, Vivian Tian wrote:
> The issue is filed for Apple.
> The question from Apple is:
> In the past, we have got MSFT test suite enabled on VMs that have
> been handed to us. I was wondering if you have something of that sort
> that we could use for this purpose.

I (at Catalyst) have been working on scripts to build a VM
automatically using packer and an Openstack VM. 

See:  
http://git.catalyst.net.nz/gw?p=samba-cloud-autobuild.git;a=tree;h=refs
/heads/master;hb=refs/heads/master

In particular:
http://git.catalyst.net.nz/gw?p=samba-cloud-autobuild.git;a=blob;f=buil
d-windows-
testclient;h=4f3f6adc6a8c36686606cb2211ffc417a406de73;hb=refs/heads/mas
ter
http://git.catalyst.net.nz/gw?p=samba-cloud-autobuild.git;a=blob;f=temp
lates/build-windows-image-
user_data.ps1;h=c9f0594b22af8cc134ca04719f0d674a1c31b661;hb=refs/heads/
master
http://git.catalyst.net.nz/gw?p=samba-cloud-autobuild.git;a=blob;f=temp
lates/build-windows-
image.json.template;h=2ee79bfb2701229820c74c565abcdeaf599c21c0;hb=refs/
heads/master

These ended up being a wrapper around the InstallPrerequisites script
in the Microsoft GitHub repo, which covers the open source testsuites,
such as FileServer.

I hope this helps,

Andrew Bartlett

-- 
Andrew Bartlett
https://samba.org/~abartlet/
Authentication Developer, Samba Team         https://samba.org
Samba Development and Support, Catalyst IT   
https://catalyst.net.nz/services/samba

**Comment by VivianTian** [comment]
Close this issue since partner has setup environment successfully now.
Thanks Andrew Bartlett and KipRepscher.
Refer to https://github.com/Microsoft/WindowsProtocolTestSuites/issues/92 for more details.
