### ISSUE TITLE
Negative tests labeled Positive

### ISSUE THREAD

**Issue by dpoe** [Microsoft/WindowsProtocolTestSuites#94]
The following two tests seem to do something not allowed in the specification and then expect the RDP client to close the connection.   This is the classic definition of a NegativeTest in the RDP suite.  Yet they are labeled "PositiveTests":

RDPEGFX_SurfaceToScreen_PositiveTest_DeleteSurface
RDPEGFX_CacheManagement_PositiveTest_EvictCache_DeleteCacheSlot

**Comment by JessieF** [comment]
Hi Daryl,

Thanks for your feedback, as we have synced before, these two cases would be labeled 'NegativeTest' in our later updates.

Actually, these two cases are designed to verify whether the client could handle the Deletion of Surface/Slot correctly, so they're labeled 'PositiveTest'. But the verification of these cases is expecting the Client to drop the connection, such a behavior should be marked as negative. 

Thanks,
Jessie

**Comment by VivianTian** [comment]
Hi, Daryl
The RDP test suite has been updated to fix this issue. 
Please get the latest version of RDP test suite and have a try.  And please let me know the result when you finished testing.
Thanks.
Vivian

**Comment by VivianTian** [comment]
Hi, Daryl
There's a configuration "DropConnectionForInvalidRequest" added in the ptfconfig file (https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/src/TestSuite/RDP_ClientTestSuite.deployment.ptfconfig). 
If you don't want to drop the connection in the RDP client side for some invalid requests, just set the "DropConnectionForInvalidRequest" to be "False". The test case will not wait until the RDP connection dropped. 
Please have a try and let me know the result.
Thanks.
Vivian

**Comment by dpoe** [comment]
Thanks!  We'll take a look at our next opportunity.   It sounds like this will be a good fix to accommodate clients that try to keep running after receiving bad data.

**Comment by VivianTian** [comment]
Sure, take your time and let me know the result. 
Thanks.

**Comment by yazeng** [comment]
Close it since we resolved this bug.
