### ISSUE TITLE
[RDP] Parsing RDP Version depends on date format

### ISSUE THREAD

**Issue by hoefleml** [Microsoft/WindowsProtocolTestSuites#95]
Hi,

I've discovered a problem running the Protocol Test Manager for RDP on my laptop. If the date and time format of the machine is set to "German (Germany)" all test cases fail with "Assert.Fail failed. RDP.Version in config file is invalid.". With the time format set to "English (United States)" everything works fine.

The cause of this issue seems to be the way of parsing the configured RDP version in TestSuites/RDP/src/TestSuite/RdpTestClassBase.cs line 129. The version string containing a dot is parsed with Double.Parse() to a double variable. But in german locales floating point numbers are represented with a comma instead of a dot. So parsing "10.0" e. g. fails.
Nevertheless it seems to me like no good idea using the double type when it comes to such things like a version number.

Regards,
Michael

**Comment by yazeng** [comment]
Hi Michael,
Thanks for your feedback.
It's interesting to know that a comma is used to represent floating point number in German.
And I agree with you, it's not proper to use a float to represent a version number.

We'll file a bug and fix it.

Thanks,
Yan

**Comment by VivianTian** [comment]
Hi, Michael
Thanks for your feedbacks about this issue. I have submitted my fix to GitHub. You can sync the latest code to get my fix. Please help to verify it is fixed.
Thanks.

**Comment by hoefleml** [comment]
Hi Vivian,

I have just pulled your fix and it works for me now. From my point of view this issue might be closed.

Thanks,
Michael
