### ISSUE TITLE
EncryptionTestCase* cases fail against Windows2012r2 with "No crypto info could be found for this session"

### ISSUE THREAD

**Issue by TesterTester111** [Microsoft/WindowsProtocolTestSuites#97]
Numerous encryption tests fail against Windows2012r2 with common failure:
System.InvalidOperationException: No crypto info could be found for this session.

All these tests expect Session Setup to fail, but still continue to TreeConnect and fail since no session established.

Suite version: 1.0.5142.0
IsGlobalEncryptDataEnabled: True 
IsGlobalRejectUnencryptedAccessEnabled: True 

Here is the stack:
Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.EnableSessionSigningAndEncryption(UInt64 sessionId, Boolean enableSigning, Boolean enableEncryption) in c:\WindowsProtocolTestSuites-staging\ProtoSDK\MS-SMB2\Client\Smb2Client.cs:line 869 at Microsoft.Protocols.TestSuites.FileSharing.Common.Adapter.Smb2FunctionalClient.EnableSessionSigningAndEncryption(Boolean enableSigning, Boolean enableEncryption) in c:\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\Common\Adapter\Smb2FunctionalClient.cs:line 401 at Microsoft.Protocols.TestSuites.FileSharing.SMB2Model.Adapter.Encryption.EncryptionAdapter.TreeConnectRequest(ConnectToShareType connectToShareType, ModelRequestType modelRequestType) in c:\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\SMB2Model\Adapter\Encryption\EncryptionAdapter.cs:line 143

**Comment by yazeng** [comment]
Hi,
Could you give me the whole log of the failed case, and also the network trace?
The call stack is not enough to debug.

Thanks,
Yan

**Comment by TesterTester111** [comment]
Hi Yan,

Please find attached, capture was taken from Auto-Detection step and includes test EncryptionTestCaseS411.

[EncryptionTestCaseS411.txt](https://github.com/Microsoft/WindowsProtocolTestSuites/files/707464/EncryptionTestCaseS411.txt)

Can't add zipped capture, how can I send you?

Thanks,
Lilia

**Comment by yazeng** [comment]
Hi Lilia,
I tried just now, I can attach a zipped capture to the issue.
Could you try again?

Thanks,
Yan

**Comment by TesterTester111** [comment]
Still can't, I get 
"We don’t support that file type.Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by yazeng** [comment]
You should zip the capture file first.

**Comment by TesterTester111** [comment]
It is zipped, send by email this time.

**Comment by yazeng** [comment]
You cannot use email to send the attachment.
I got one capture on my environment. Maybe you can take a look and see what's the difference.
[EncryptionTestCaseS411.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/707617/EncryptionTestCaseS411.zip)

**Comment by TesterTester111** [comment]
![encryptiontestcases411_capture](https://cloud.githubusercontent.com/assets/25079571/21975979/30c95c30-dbd8-11e6-8060-3f07fc48a5ac.png)

Please rename to pcapng.

**Comment by yazeng** [comment]
Thanks Lilia, I can repro the issue in my environment.
I did not enable GlobalEncryptData when I trace the capture.
When I did enable it, I can repro the issue.

I'll file a bug for this issue and fix it later.
And you can disable GlableEncryptData if it blocked your testing.

Thank your for reporting this issue!

**Comment by chenlu0616** [comment]
Hi, Lilia

We have updated the encryption model and the related test cases, and you can sync the latest code to verify the issue. Let me know if there is any problem. Thanks!

Thanks,
Lu

**Comment by yazeng** [comment]
Close this issue since no update for a long time.
